### ISSUE TITLE
Gradio Showcase报错

### ISSUE THREAD

**Issue by Borye** [towhee-io/examples#105]
Image Search Engine案例，最后一步Gradio报错如下：

2022-08-26 23:06:57,117 - 12779106304 - decorators.py-decorators:95 - ERROR: RPC error: [search], <MilvusException: (code=1, message=checkIfLoaded failed when search, collection:reverse_image_search_norm, partitions:[], err = showPartitions failed, collection = reverse_image_search_norm, partitionIDs = [], reason = collection 435558044005564417 has not been loaded into QueryNode)>, <Time:{'RPC start': '2022-08-26 23:06:57.105122', 'RPC error': '2022-08-26 23:06:57.117755'}>
Traceback (most recent call last):
  File "/Users/borye/miniforge3/lib/python3.9/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/Users/borye/miniforge3/lib/python3.9/site-packages/gradio/blocks.py", line 645, in process_api
    output = self.postprocess_data(fn_index, predictions, state)
  File "/Users/borye/miniforge3/lib/python3.9/site-packages/gradio/blocks.py", line 594, in postprocess_data
    prediction_value = predictions[i]
TypeError: '_Reason' object is not subscriptable

**Comment by shiyu22** [comment]
I think you are running this notebook, the error show that `collection 435558044005564417 has not been loaded into QueryNode`, so please run `norm_collection.load()` before searching.

**Comment by Borye** [comment]
Solved, many thanks.
