### ISSUE TITLE
TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by cuisws** [towhee-io/examples#197]
我在运行search_article_in_medium.ipynb文件
执行下面代码的时候
from towhee import ops, pipe, DataCollection

insert_pipe = (pipe.input('df')
                   .flat_map('df', 'data', lambda df: df.values.tolist())
                   .map('data', 'res', ops.ann_insert.milvus_client(host='127.0.0.1',
                                                                    port='19530',
                                                                    collection_name='search_article_in_medium'))
                   .output('res')
)
错误信息：
Traceback (most recent call last):
  File "D:\IT\python\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-97fb9657005d>", line 3, in <cell line: 3>
    insert_pipe = (pipe.input('df')
  File "D:\IT\python\Python38\lib\site-packages\towhee\runtime\pipeline.py", line 103, in output
    dag_dict = deepcopy(self._dag)
  File "D:\IT\python\Python38\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "D:\IT\python\Python38\lib\copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "D:\IT\python\Python38\lib\copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.lock' object

请问下是什么原因，怎么解决
我的towhee版本是 0.9.0

**Comment by junjiejiangjjj** [comment]
The examples require towhee 1.0.0rc1, which can be installed with pip install towhee==1.0.0rc1

**Comment by cuisws** [comment]
> 示例需要 towhee 1.0.0rc1，可以使用 pip install towhee==1.0.0rc1 安装

Thank you for your reminder. I ran successfully
