### ISSUE TITLE
ModuleNotFoundError: No module named 'towhee.models.utils.video_transforms'

### ISSUE THREAD

**Issue by tcexeexe** [towhee-io/examples#203]
Hello~
I am trying the example `video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb`, but an error occurred that 
My towhee version is 1.0.0. Dose any one konw how to solve the problem?

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb 单元格 11 in 8
      [3](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2) from towhee.datacollection import DataCollection
      [5](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4) collection = create_milvus_collection('timesformer', 768)
      [7](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6) insert_pipe = (
----> [8](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=7)     pipe.input('csv_path')
      [9](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=8)         .flat_map('csv_path', ('id', 'path', 'label'), read_csv)
     [10](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=9)         .map('id', 'id', lambda x: int(x))
     [11](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=10)         .map('path', 'frames', ops.video_decode.ffmpeg(sample_type='uniform_temporal_subsample', args={'num_samples': 8}))
     [12](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=11)         .map('frames', ('labels', 'scores', 'features'), ops.action_classification.timesformer(skip_preprocess=True))
     [13](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=12)         .map('features', 'features', ops.towhee.np_normalize())
     [14](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=13)         .map(('id', 'features'), 'insert_res', ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='timesformer'))
     [15](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=14)         .output()
     [16](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=15) )
     [18](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=17) insert_pipe('reverse_video_search.csv')
     [20](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D?line=19) collection.load()

File [~/anaconda3/envs/towhee/lib/python3.8/site-packages/towhee/runtime/pipeline.py:116](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2253485445435f646576656c6f70227d.vscode-resource.vscode-cdn.net/home/image_check/code/examples/video/reverse_video_search/~/anaconda3/envs/towhee/lib/python3.8/site-packages/towhee/runtime/pipeline.py:116), in Pipeline.output(self, *output_schema, **config_kws)
    113 dag_dict[self._clo_node]['next_nodes'].append(uid)
    115 run_pipe = RuntimePipeline(dag_dict, config=config_kws)
--> 116 run_pipe.preload()
    117 return run_pipe

File [~/anaconda3/envs/towhee/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py:140](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2253485445435f646576656c6f70227d.vscode-resource.vscode-cdn.net/home/image_check/code/examples/video/reverse_video_search/~/anaconda3/envs/towhee/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py:140), in RuntimePipeline.preload(self)
...
    from .timesformer import Timesformer
  File "/home/image_check/.towhee/operators/action-classification/timesformer/versions/main/timesformer.py", line 13, in 
    from towhee.models.utils.video_transforms import transform_video
ModuleNotFoundError: No module named 'towhee.models.utils.video_transforms'
```

**Comment by junjiejiangjjj** [comment]
pip install -U towhee.models

**Comment by tcexeexe** [comment]
> pip install -U towhee.models
Hello, l have solve the above mention problem by you method, but another problem occcurred： 
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb 单元格 14 in 8
      [3](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2) projection_matrix = np.random.normal(scale=1.0, size=(768, 128))
      [5](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4) collection = create_milvus_collection('timesformer_128', 128)
      [7](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6) insert_pipe = (
----> [8](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=7)     pipe.input('csv_path')
      [9](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=8)         .flat_map('csv_path', ('id', 'path', 'label'), read_csv)
     [10](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=9)         .map('id', 'id', lambda x: int(x))
     [11](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=10)         .map('path', 'frames', ops.video_decode.ffmpeg(sample_type='uniform_temporal_subsample', args={'num_samples': 8}))
     [12](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=11)         .map('frames', ('labels', 'scores', 'features'), ops.action_classification.timesformer(skip_preprocess=True))
     [13](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=12)         .map('features', 'features', lambda x: np.dot(x, projection_matrix))
     [14](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=13)         .map('features', 'features', ops.towhee.np_normalize())
     [15](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=14)         .map(('id', 'features'), 'insert_res', ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='timesformer_128'))
     [16](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=15)         .output()
     [17](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=16) )
     [19](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=18) insert_pipe('reverse_video_search.csv')
     [21](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a2253485445435f646576656c6f70227d/home/image_check/code/examples/video/reverse_video_search/2_deep_dive_reverse_video_search.ipynb#X21sdnNjb2RlLXJlbW90ZQ%3D%3D?line=20) collection.load()

File [~/anaconda3/envs/towhee/lib/python3.8/site-packages/towhee/runtime/pipeline.py:116](https://vscode-remote+ssh-002dremote-002b7b22686f73744e616d65223a2253485445435f646576656c6f70227d.vscode-resource.vscode-cdn.net/home/image_check/code/examples/video/reverse_video_search/~/anaconda3/envs/towhee/lib/python3.8/site-packages/towhee/runtime/pipeline.py:116), in Pipeline.output(self, *output_schema, **config_kws)
    113 dag_dict[self._clo_node]['next_nodes'].append(uid)
    115 run_pipe = RuntimePipeline(dag_dict, config=config_kws)
--> 116 run_pipe.preload()
    117 return run_pipe
...
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/image_check/anaconda3/envs/towhee/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?fbb60b74-c7c1-4fc4-87eb-2f8c8a75a457) or open in a [text editor](command:workbench.action.openLargeOutput?fbb60b74-c7c1-4fc4-87eb-2f8c8a75a457). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
```

Can you give me some advices about it? 
I have put the "reverse_video_search.csv"and the following forder in the peer directory.

**Comment by junjiejiangjjj** [comment]
Seems downloading the weights failed， rm the local weight, and try again, weights in ~/.cache/towhee/TimeSformer_divST*
